from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
CAPTURE_DIR = ROOT / "ir_captures"
OUT_PATHS = [
    ROOT / "home_controller" / "ir_commands.h",
    ROOT / "raspberry_pi_transfer" / "ir_commands.h",
]

COMMAND_ORDER = [
    *(f"on_cool_{temperature}" for temperature in range(18, 29)),
    *(f"set_cool_{temperature}" for temperature in range(18, 29)),
    "ac_off",
    "on_dry",
    "dry_off",
]

RAW_RE = re.compile(r"IR_RAW_DATA:\s*(.+)")


def command_name(file_stem):
    return file_stem.upper()


def array_name(file_stem):
    return "IR_" + file_stem.upper()


def parse_raw_file(path):
    text = path.read_text(encoding="utf-8")
    match = RAW_RE.search(text)
    if not match:
        raise ValueError(f"IR_RAW_DATA line not found: {path}")

    values = []
    for item in match.group(1).split(","):
        item = item.strip()
        if not item:
            continue
        values.append(int(item[1:]))

    if not values:
        raise ValueError(f"No raw values parsed: {path}")

    return values


def wrap_values(values, indent="  ", width=100):
    lines = []
    current = indent

    for index, value in enumerate(values):
        piece = f"{value}"
        if index < len(values) - 1:
            piece += ","

        if len(current) + len(piece) + 1 > width:
            lines.append(current.rstrip())
            current = indent + piece + " "
        else:
            current += piece + " "

    if current.strip():
        lines.append(current.rstrip())

    return "\n".join(lines)


def main():
    commands = []
    for stem in COMMAND_ORDER:
        path = CAPTURE_DIR / f"{stem}.txt"
        if not path.exists():
            continue

        commands.append((stem, parse_raw_file(path)))

    if not commands:
        raise SystemExit("No IR capture files found.")

    lines = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "#include <avr/pgmspace.h>",
        "",
        "// Generated by tools/generate_ir_header.py from ir_captures/*.txt.",
        "// Do not edit raw values here by hand; edit capture files and regenerate.",
        "",
    ]

    for stem, values in commands:
        lines.append(f"const unsigned int {array_name(stem)}[] PROGMEM = {{")
        lines.append(wrap_values(values))
        lines.append("};")
        lines.append("")

    lines.append("#define FOR_EACH_IR_COMMAND(M) \\")
    for index, (stem, _values) in enumerate(commands):
        suffix = " \\" if index < len(commands) - 1 else ""
        name = command_name(stem)
        lines.append(f'  M({name}, "{name}", IR_{name}){suffix}')
    lines.append("")

    content = "\n".join(lines)
    for out_path in OUT_PATHS:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8", newline="\n")
        print(out_path)


if __name__ == "__main__":
    main()
